toolchain = 'arm-none-eabi'
c_flags = [
	'-Os',
	'-nostdlib',
	'-nostartfiles',
	'-ffunction-sections',
	'-fdata-sections',
	'-march=armv7-m',
	'-mtune=cortex-m3',
	'-mthumb',
	'-mfloat-abi=soft',
	'-ffreestanding',
]
ld_flags = [
	'-lm',
	'-lc',
	'-lgcc',
	'-lnosys',
	'-nostdlib',
	'-nostartfiles',
	'-fdata-sections',
	'-ffunction-sections',
	'--specs=nano.specs',
	'--specs=nosys.specs',
	'-Wl,--gc-sections',
	'-march=armv7-m',
	'-mtune=cortex-m3',
	'-mthumb',
]
source = [
#	'startup.c',
]

[dependencies]
cmsis-5 = {}
cmsis-dfp-sam3u = {}
#tinyusb = { target = 'microchip/sam3u' }
