name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
    - name: Update the system and install dependencies
      run: pacman -Syu --noconfirm --noprogressbar --needed clang git python-pip

    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Container permissions
      run: git config --global --add safe.directory '*'

    - name: Run pre-commit
      uses:  before-commit/run-action@v2.0.3
